function tau = trunk_torque(q0,q2,m_4,M_4,N_leg,F1_leg,N_trunk,F1_trunk)
% TRUNK_TORQUE, determine the required torque by the trunk based on the 
%   model of the trunk. Inputs are
%   (q0,q2,m_4,N_leg,F1_leg,N_trunk,F1_trunk):
%   -   q0, joint angle 0 (ankle)
%   -   q2, joint angle 2 (hip)
%   -   m_4, mass of the arms
%   -   M_4, moment generated by the arms
%   -   N_leg, number of springs in leg
%   -   F1_leg, load of springs in leg
%   -   N_trunk, number of springs in trunk
%   -   F1_trunk, load of springs in trunk


    